config/routes.rb
Rails.application.routes.draw do  

  devise_for :users

  resources :tasks, only: [:edit, :update]
  
  resources :projects do 
    resources :favorites,       only: [:create, :destroy]
    resources :project_members, only: [:create, :destroy]
    resources :tasks
    resources :discussions
  end

  resources :discussions, only: [] do 
    resources :comments, except: [:show]
  end

  get '/favorites' => 'favorites#index'

  get 'projects/:id/upvote' => 'projects#upvote'
  get 'projects/:id/downvote' => 'projects#downvote'

  root 'projects#index'

  get 'home' => 'home#home'
  get 'about' => 'home#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :discussion
  belongs_to :user

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  validates :title, presence: true

  belongs_to :project
  belongs_to :user

  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: {scope: :project_id}
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, presence: true, uniqueness: true
  has_one :vote, dependent: :destroy

  has_many :tasks
  has_many :discussions

  has_many :project_members, dependent: :destroy
  has_many :users, through: :project_members

  has_many :favorites, dependent: :destroy
  has_many :users_favorited, through: :favorites, source: :user

  has_many :taggers, dependent: :destroy
  has_many :tags, through: :taggers

  belongs_to :user

  def project_member?(user)
    project_members.exists?(user: user)
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end


  private

  def self.search(search)
    if search
      search = "%#{search}%"
      includes(:tags).
      references(:tags).
      where('projects.title ILIKE ? OR projects.description ILIKE ? OR tags.name ILIKE ?',
        search, search, search).
      distinct('projects.id').
      order("projects.updated_at DESC")
    else
      all.order("updated_at DESC")
    end
  end

end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggers, dependent: :destroy
  has_many :projects, through: :taggers

  validates :name, presence: true, uniqueness: true

end

app/models/tagger.rb
class Tagger < ActiveRecord::Base
  belongs_to :project
  belongs_to :tag
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  belongs_to :user


  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :project_members, dependent: :destroy
  has_many :member_of_projects, through: :project_members, source: :project

  has_many :favorites, dependent: :destroy
  has_many :favorite_projects, through: :favorites, source: :project

  def name_display 
    if first_name || last_name
      ["#{first_name}", "#{last_name}"].map(&:capitalize).join(" ").squeeze(" ").strip
    else
      email
    end
  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :project

  def up
    self.upvotes += 1
    self.save
  end

  def down
    self.downvotes += 1
    self.save
  end

  def score
    self.upvotes - self.downvotes
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :find_project, only: [:show, :new, :index, :create, :edit, :update, :destroy]
  before_action :find_discussion, only: [:show, :edit, :update, :destroy]

  def index
    @discussions = @project.discussions
  end

  def show
    @comment = Comment.new
  end

  def new
    @discussion = @project.discussions.new
  end

  def create
    @discussion = @project.discussions.new(discussion_params)
    @discussion.user = current_user
    if @discussion.save
      redirect_to project_discussions_path(@project), notice: "Discussion successfully created!"
    else
      flash.now[:alert] = "Problem creating discussion"
      render :new
    end
  end

  def edit
    
  end

  def update
    if current_user == @discussion.user
      if @discussion.update_attributes(discussion_params)
        redirect_to project_discussions_path(@project), notice: "Discussion successfully updated!"
      else
        flash.now[:alert] = "Problem updating discussion"
        render :edit
      end
    else
      redirect_to project_discussions_path(@project), alert: "That's not yours buster"
    end
  end

  def destroy
    if current_user == @discussion.user
      @discussion.destroy
      redirect_to project_discussions_path, notice: "Discussion successfully destroyed."
    else
      redirect_to project_discussions_path, alert: "That's not yours buster"
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_discussion
    @discussion = @project.discussions.find(params[:id])
  end

  def discussion_params
    params.require(:discussion).permit(:title, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :find_task, only: [:edit, :update]

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.user = current_user
    respond_to do |format|
      if @task.save
        flash.now[:notice] = "Task successfully created!"
        format.html { redirect_to @project, notice: "Task successfully created!" }
        format.js   { render }
      else
        flash.now[:alert] = "Problem with creating task" 
        format.html { render "projects/show" }
        format.js   { render }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js { render }
    end
  end

  def update
    if current_user == @task.user
      respond_to do |format|
        if @task.update_attributes(task_params)
          format.html { redirect_to @project, notice: "Task successfully updated" }
          format.js   { render }
        else
          format.html { redirect_to @project, alert: "Problem updating task." }
          format.js   { render }
        end
      end
    else
      redirect_to @project, alert: "That's not yours buster >:("
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      if current_user == @task.user
        @task.destroy
        format.html { redirect_to @project, notice: "Task successfully deleted" }
        format.js   { render }
      else
        format.html { redirect_to @project, alert: "That's not yours buster >:(" }
        format.js   { render }
      end
    end
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :body, :due_date, :status)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def update

  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper

  
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def user_project_checker
    @project.user == current_user
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/discussions/_form.html.haml
= form_for [@project,@discussion] do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  = f.submit "Save Discussion", class: "btn btn-default"

app/views/discussions/edit.html.haml
%h1
  Editing #{@discussion.title}
= render 'form'

app/views/discussions/index.html.haml
= link_to "Back to Project", project_path(@project), class: "btn btn-primary"
.clearfix
%h1
  Discussions for *#{@project.title}*
.row
  = link_to "Create New Discussion", new_project_discussion_path(@project), class: "btn btn-success getaway"
- @discussions.each_slice(3) do |discussion_group|
  .row
    - discussion_group.each do |discussion|
      .col-md-4.well.cre8
        %h2= link_to discussion.title, project_discussion_path(@project, discussion)
        .row.getaway
          %small By #{discussion.user.name_display}
        %p= truncate(discussion.description, length: 200)

app/views/discussions/new.html.haml
%h1 Create A New Discussion
= render 'form'

app/views/discussions/show.html.haml
= link_to "Back to Discussions", project_discussions_path(@project), class: "btn btn-primary"
.clearfix
.well.col-md-8.col-md-offset-2
  .well.row
    %h1= @discussion.title
    %p= simple_format @discussion.description
    %hr
    by #{@discussion.user.name_display}
    .pull-right
      -if @discussion.user == current_user  
        = link_to "Edit", edit_project_discussion_path(@project, @discussion), class: "btn btn-info getaway"
        = button_to "Destroy",  [@project, @discussion], method: :delete, data: { confirm: "Are you sure you want to delete this discussion?" }, class: "btn btn-danger"
  .comments
    - @discussion.comments.each do |comment|
      = render partial: "comments/comment", locals: { comment: comment }
  = render "comments/comment_form"

#editComment.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editCommentLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#taskLabel.modal-title Edit Comment
      #edit-errors
      .modal-body.edit-modal
      .modal-footer