config/routes.rb
Rails.application.routes.draw do  

  devise_for :users

  resources :tasks, only: [:edit, :update]
  
  resources :projects do 
    resources :favorites,       only: [:create, :destroy]
    resources :project_members, only: [:create, :destroy]
    resources :tasks
    resources :discussions
  end

  resources :discussions, only: [] do 
    resources :comments, except: [:show]
  end

  get '/favorites' => 'favorites#index'

  get 'projects/:id/upvote' => 'projects#upvote'
  get 'projects/:id/downvote' => 'projects#downvote'

  root 'projects#index'

  get 'home' => 'home#home'
  get 'about' => 'home#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :discussion
  belongs_to :user

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  validates :title, presence: true

  belongs_to :project
  belongs_to :user

  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: {scope: :project_id}
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, presence: true, uniqueness: true
  has_one :vote, dependent: :destroy

  has_many :tasks
  has_many :discussions

  has_many :project_members, dependent: :destroy
  has_many :users, through: :project_members

  has_many :favorites, dependent: :destroy
  has_many :users_favorited, through: :favorites, source: :user

  has_many :taggers, dependent: :destroy
  has_many :tags, through: :taggers

  belongs_to :user

  def project_member?(user)
    project_members.exists?(user: user)
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end


  private

  def self.search(search)
    if search
      search = "%#{search}%"
      includes(:tags).
      references(:tags).
      where('projects.title ILIKE ? OR projects.description ILIKE ? OR tags.name ILIKE ?',
        search, search, search).
      distinct('projects.id').
      order("projects.updated_at DESC")
    else
      all.order("updated_at DESC")
    end
  end

end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggers, dependent: :destroy
  has_many :projects, through: :taggers

  validates :name, presence: true, uniqueness: true

end

app/models/tagger.rb
class Tagger < ActiveRecord::Base
  belongs_to :project
  belongs_to :tag
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  belongs_to :user


  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :project_members, dependent: :destroy
  has_many :member_of_projects, through: :project_members, source: :project

  has_many :favorites, dependent: :destroy
  has_many :favorite_projects, through: :favorites, source: :project

  def name_display 
    if first_name || last_name
      ["#{first_name}", "#{last_name}"].map(&:capitalize).join(" ").squeeze(" ").strip
    else
      email
    end
  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :project

  def up
    self.upvotes += 1
    self.save
  end

  def down
    self.downvotes += 1
    self.save
  end

  def score
    self.upvotes - self.downvotes
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_project, only: [:show, :edit, :update, :destroy, :upvote, :downvote]


  def index
    @projects = Project.paginate(page: params[:page], per_page: 10).search(params[:search])
  end

  def show
    session[:return_to] ||= request.referer
    @done            = @project.tasks.where("status = true")
    @notdone         = @project.tasks.where("status = false")
    @task            = Task.new
    @users           = User.all
    @tags            = @project.tags
    @project_members = @project.project_members
    @favorite        = @project.favorites.where(user: current_user).first
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      @project.vote = Vote.new
      redirect_to projects_path, notice: "Project created successfully"
    else
      flash.now[:alert] = "Problem creating project"
      render :new
    end
  end

  def edit
  end

  def update
    if current_user == @project.user
      if @project.update_attributes(project_params)
        redirect_to @project, notice: "Project updated successfully"
      else
        flash.now[:alert] = "Problem updating project"
        render :edit
      end
    else
      redirect_to @project, alert: "That's not yours buster >:("
    end
  end

  def destroy
    if current_user == @project.user
      @project.destroy
      redirect_to projects_path, notice: "Project deleted successfully"
    else
      redirect_to @project, alert: "That's not yours buster >:("
    end
  end

  def upvote
    @project.vote.up
    redirect_to projects_path(page: params[:page])
  end

  def downvote
    @project.vote.down
    redirect_to projects_path(page: params[:page])
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    puts params.inspect
    params.require(:project).permit(:title, :description, :due_date, :votes, {tag_ids: []})
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :find_task, only: [:edit, :update]

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.user = current_user
    respond_to do |format|
      if @task.save
        flash.now[:notice] = "Task successfully created!"
        format.html { redirect_to @project, notice: "Task successfully created!" }
        format.js   { render }
      else
        flash.now[:alert] = "Problem with creating task" 
        format.html { render "projects/show" }
        format.js   { render }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js { render }
    end
  end

  def update
    if current_user == @task.user
      respond_to do |format|
        if @task.update_attributes(task_params)
          format.html { redirect_to @project, notice: "Task successfully updated" }
          format.js   { render }
        else
          format.html { redirect_to @project, alert: "Problem updating task." }
          format.js   { render }
        end
      end
    else
      redirect_to @project, alert: "That's not yours buster >:("
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      if current_user == @task.user
        @task.destroy
        format.html { redirect_to @project, notice: "Task successfully deleted" }
        format.js   { render }
      else
        format.html { redirect_to @project, alert: "That's not yours buster >:(" }
        format.js   { render }
      end
    end
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :body, :due_date, :status)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def update

  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper

  
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def user_project_checker
    @project.user == current_user
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/projects/_form.html.haml
- if @project.errors.any?
  %ul
    - @project.errors.full_messages.each do |err|
      %li= err
= form_for @project do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :due_date
    = f.text_field :due_date, class: "form-control"
  .form-group
    = f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name
  = f.submit class: "btn btn-default"

app/views/projects/edit.html.haml
%h1 Editing Project
= render 'form'

app/views/projects/index.html.haml
%h1.col-xs-8.col-xs-offset-2.col-md-6.col-md-offset-4 Projects Index
%div
  .row
    .col-xs-9.col-md-6.col-md-offset-3
      = form_tag projects_path, method: 'get' do
        = text_field_tag :search, params[:search], class: "form-control"
    .col-xs-3.col-md-3
      = submit_tag "Search", name: nil, class: "btn btn-info"
  .row.getaway
    .col-md-2.col-md-offset-2.col-xs-offset-3.col-xs-6
      - if user_signed_in?
        = link_to "Create New Project", new_project_path, class: "btn btn-primary"
  .row
    .col-xs-12.col-md-8.col-md-offset-2
      - @projects.each do |project|
        .row.well
          %div
            = link_to "<i class='glyphicon glyphicon-arrow-up'></i>".html_safe, { action: "upvote", id: project.id, page: params[:page] }
            = project.vote.score
            = link_to "<i class='glyphicon glyphicon-arrow-down'></i>".html_safe, { action: "downvote", id: project.id, page: params[:page] }
          %div
            %h2 
              #{link_to project.title, project}
              %small By #{project.user.name_display}
            %p= truncate(project.description, length: 500)
            %p
              Due on: #{project.due_date}
.col-md-offset-4.col-md-6
  = will_paginate @projects, renderer: BootstrapPagination::Rails

app/views/projects/new.html.haml
%h1 Create the Project
= render 'form'

app/views/projects/show.html.haml
.row.well
  .pull-right
    = link_to "Discuss This Project" , project_discussions_path(@project), class: "btn btn-info"
  %h1
    = @project.title
    %small #{@project.user.name_display}
  .row
    .col-md-9
      %p= simple_format @project.description
    - if user_signed_in?
      .col-md-3
        - @users.each do |user|
          .row
            - unless @project.project_member?(user.id)
              = link_to "<i class='glyphicon glyphicon-plus'></i> #{user.name_display}".html_safe, project_project_members_path(@project, ProjectMember.new, :user_id => user.id), method: :post
        - @project_members.each do |pm|
          .row
            = link_to "<i class='glyphicon glyphicon-minus'></i> #{pm.user.name_display}".html_safe, [@project, pm], method: :delete, style: "color: red"
  %br/
  .row
    %p
      Due on: #{@project.due_date}
  %hr/
  - if user_project_checker
    = link_to "Edit", edit_project_path, class: "btn btn-info"
    = link_to "Destroy", @project, method: :delete, data: { confirm: "Are you sure you want to delete this project?" }, class: "btn btn-danger"
  - if user_signed_in?
    - if @project.favorited_by?(current_user)
      =link_to "<i class='glyphicon glyphicon-star'></i>".html_safe, [@project, @favorite], class: "btn btn-default", method: :delete
    - else
      =link_to "<i class='glyphicon glyphicon-star-empty'></i>".html_safe, [@project, Favorite.new], class: "btn btn-default", method: :post
  %hr/
  .row
    .col-md-1
      %h4{style: "color: grey;"} Tags: 
    - @tags.each do |tag|
      .col-xs-2.col-sm-2.col-md-1.well{style: "font-size: 0.8em; text-align: center;"}
        = tag.name
- if user_signed_in?
  .row
    %h2 Create New Task
    .task-errors
    = form_for [@project, @task], remote: true do |f|
      .col-xs-12.col-md-6
        = f.label :title
        = f.text_field :title, class: "form-control", id: "new-task-title"
      .clearfix
      .col-xs-12.col-md-6
        = f.label :body
        = f.text_area :body, class: "form-control", id: "new-task-body"
      .clearfix
      .col-xs-12.col-md-6
        = f.label :due_date
        = f.text_field :due_date, class: "form-control", id: "new-task-due-date"
      .clearfix
      = f.submit class: "btn btn-success getaway"
    %hr/
%h2 Incomplete Tasks
%table.table.table-hover#incompletes
  %tr
    %th Title
    %th Body
    %th Due Date
    %th Actions
  - @notdone.each do |task|
    = render partial: "/tasks/task", locals: { task: task }

%hr/
%h2 Completed Tasks
%table.table.table-hover#completes
  %tr
    %th Title
    %th Body
    %th Due Date
    %th Actions
  - @done.each do |task|
    = render partial: "/tasks/task", locals: { task: task }

#editTask.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editTaskLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#taskLabel.modal-title Edit Task
      #edit-errors
      .modal-body.edit-modal
      .modal-footer