config/routes.rb
Rails.application.routes.draw do  

  devise_for :users

  resources :tasks, only: [:edit, :update]
  
  resources :projects do 
    resources :favorites,       only: [:create, :destroy]
    resources :project_members, only: [:create, :destroy]
    resources :tasks
    resources :discussions
  end

  resources :discussions, only: [] do 
    resources :comments, except: [:show]
  end

  get '/favorites' => 'favorites#index'

  get 'projects/:id/upvote' => 'projects#upvote'
  get 'projects/:id/downvote' => 'projects#downvote'

  root 'projects#index'

  get 'home' => 'home#home'
  get 'about' => 'home#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :discussion
  belongs_to :user

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  validates :title, presence: true

  belongs_to :project
  belongs_to :user

  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: {scope: :project_id}
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, presence: true, uniqueness: true
  has_one :vote, dependent: :destroy

  has_many :tasks
  has_many :discussions

  has_many :project_members, dependent: :destroy
  has_many :users, through: :project_members

  has_many :favorites, dependent: :destroy
  has_many :users_favorited, through: :favorites, source: :user

  has_many :taggers, dependent: :destroy
  has_many :tags, through: :taggers

  belongs_to :user

  def project_member?(user)
    project_members.exists?(user: user)
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end


  private

  def self.search(search)
    if search
      search = "%#{search}%"
      includes(:tags).
      references(:tags).
      where('projects.title ILIKE ? OR projects.description ILIKE ? OR tags.name ILIKE ?',
        search, search, search).
      distinct('projects.id').
      order("projects.updated_at DESC")
    else
      all.order("updated_at DESC")
    end
  end

end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggers, dependent: :destroy
  has_many :projects, through: :taggers

  validates :name, presence: true, uniqueness: true

end

app/models/tagger.rb
class Tagger < ActiveRecord::Base
  belongs_to :project
  belongs_to :tag
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  belongs_to :user


  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :project_members, dependent: :destroy
  has_many :member_of_projects, through: :project_members, source: :project

  has_many :favorites, dependent: :destroy
  has_many :favorite_projects, through: :favorites, source: :project

  def name_display 
    if first_name || last_name
      ["#{first_name}", "#{last_name}"].map(&:capitalize).join(" ").squeeze(" ").strip
    else
      email
    end
  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :project

  def up
    self.upvotes += 1
    self.save
  end

  def down
    self.downvotes += 1
    self.save
  end

  def score
    self.upvotes - self.downvotes
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def user_project_checker
    @project.user == current_user
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PM Tool
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.page-header
      %h1 Project Management Tool
      %nav.navbar.navbar-default
        %ul.nav.navbar-nav
          %li= link_to "Home", root_path
          %li= link_to "About", about_path
          %li= link_to "Projects Index", projects_path
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to "Favorites", favorites_path
            %li= link_to current_user.name_display, edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Sign In", new_user_session_path

    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - elsif flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield

app/views/shared/_standard_errors.html.haml
- if object.errors.any?
  %ul
    - object.errors.full_messages.each do |err|
      %li= err 